### ISSUE TITLE
Can you use panel-highcharts in Google Colab?

### ISSUE THREAD

**Issue by sugatoray** [MarcSkovMadsen/panel-highcharts#1]
I tried using it. But the chart object does not show up in Google Colab. Is there a fix to this? Since, altair, plotly, bokeh -- all can be shown in colab, can there be something similar for panel-highcharts?

Thank you.

**Comment by MarcSkovMadsen** [comment]
Hi @sugatoray . Thanks for reaching out.

Could you try adding `pn.extension(comms='colab')` at the top of the notebook? 

C.f. https://github.com/holoviz/panel#google-colab.

I would be happy to hear if it solves the problem. Thanks.
