### ISSUE TITLE
 the highcharts-more.js file must be loaded

### ISSUE THREAD

**Issue by sygspjlsj** [MarcSkovMadsen/panel-highcharts#2]
missingModuleFor: packedbubble;

 the highcharts-more.js file must be loaded

**Comment by MarcSkovMadsen** [comment]
Hi @sygspjlsj 

Thanks for reaching out. You can load additional js modules using `panel_highcharts.config.js_files`

![image](https://user-images.githubusercontent.com/42288570/118542953-f7a6bb80-b753-11eb-9d3f-390032862391.png)


You can now find a working example on binder https://mybinder.org/v2/gh/marcskovmadsen/panel-highcharts/HEAD?urlpath=lab/tree/examples/PackedBubble.ipynb

**Comment by MarcSkovMadsen** [comment]
https://user-images.githubusercontent.com/42288570/118543492-9b906700-b754-11eb-8da0-83a0eb57cc77.mp4
