### ISSUE TITLE
support to variwide module

### ISSUE THREAD

**Issue by vincent-cph** [MarcSkovMadsen/panel-highcharts#4]
Missing support to the module variwide: https://www.highcharts.com/docs/chart-and-series-types/variwide-chart#!
A quite useful module for plotting supply stacks for example ;) 
It is also not present in HS file service https://code.highcharts.com/ and not part of `panel_highcharts.config.js_files `

**Comment by MarcSkovMadsen** [comment]
Implemented and new package released. Could you test if it works for you and let me know? Thanks.

Thanks for reaching out and helping to improve this package 👍 

![image](https://user-images.githubusercontent.com/42288570/129573062-fb6f3443-31c5-4918-8d25-e8c3971117c8.png)

**Comment by vincent-cph** [comment]
Works like a charm, thx!
