### ISSUE TITLE
catching JS errors

### ISSUE THREAD

**Issue by vincent-cph** [MarcSkovMadsen/panel-highcharts#5]
Would be pretty cool if the JS errors like below could be somehow caught and raised as a python exception?

![image](https://user-images.githubusercontent.com/43907548/129484060-a331f2fe-7596-409d-8cf0-3c12fad2e6b0.png)

**Comment by MarcSkovMadsen** [comment]
That would definitely be useful and cool. But it should be a request for the Panel package.
