### ISSUE TITLE
Highstock chart buttons/slider always appear in the front of the panel dashboard

### ISSUE THREAD

**Issue by thetradingflow** [MarcSkovMadsen/panel-highcharts#8]
I created a simple dashboard with `panel.Tabs`. When I add a highstock chart to a a tab using `panel_highcharts` the slider and the button of the chart appear in every tabs. Here is a reproducible example:

```python
import panel_highcharts as ph
import panel as pn
import pandas as pd
import numpy as np


pn.extension('highstock')


def convert_returns(returns):
    prices = (1 + returns).cumprod().to_list()
    timestamps = list(returns.index.map(lambda x: int(float(x.to_datetime64()) / 1_000_000)))
    return list(map(list, zip(timestamps, prices)))


def plot_returns_highcharts(returns):
    data = convert_returns(returns)
    configuration = {
        "rangeSelector": {
            "inputEnabled": False,
        },
        "series": [
            {"name": "series", "type": "line", "data": data, "tooltip": {"valueDecimals": 2}}
        ],
        "yAxis": {
            "labels": {
                "formatter": """function () {
                    return (this.value > 0 ? ' + ' : '') + this.value + '%';
                }"""
            },
            "plotLines": [{
                "value": 0,
                "width": 2,
                "color": 'silver'
            }]
        },
        "plotOptions": {
            "series": {
                "compare": 'percent',
                "showInNavigator": True
            }
        },
    }
    chart = ph.HighStock(object=configuration)
    return chart

returns = pd.Series(np.random.normal(0, 0.01, 1_000),
                    index=pd.date_range("2000-01-01", freq="D", periods=1_000))

dashboard = pn.Column(
    pn.pane.Markdown("## Dashboard"),
    pn.Tabs(
        ("description", pn.pane.Str("blablabla...")),
        ("chart", plot_returns_highcharts(returns)),
        tabs_location="left"
    )
)

dashboard
```

Here's the output:

![Screenshot from 2022-02-19 12-45-35](https://user-images.githubusercontent.com/59395196/154799420-6447464a-c282-4b65-990a-661886553828.png)

The tab `chart` is displayed properly:

![Screenshot from 2022-02-19 12-46-34](https://user-images.githubusercontent.com/59395196/154799459-90eee157-5925-4719-99fc-26a0df3c9d71.png)

Sorry if it's just a setting I wrongly configured, I spent quite some time on it and couldn't find what's wrong. Thank you!

**Comment by govinda18** [comment]
Hi @thetradingflow,

This is actually a bug in the upstream highcharts library. Panel uses div visibility for hiding the tabs. However, highcharts range selector and navigator do not seem to hide visibility based on ancestor visibility.

Check the issue I logged: https://github.com/highcharts/highcharts/issues/16901

As suggested, you can add the CSS they recommended to your app to avoid this behaviour.

**Comment by MarcSkovMadsen** [comment]
Thanks, The @thetradingflow and @govinda18 

The issue https://github.com/highcharts/highcharts/issues/16901 mentions a work around is to add the `css`

```css
.highcharts-range-selector-buttons > g {
	visibility: unset;
}

.highcharts-navigator {
	visibility: unset;
}
```

https://user-images.githubusercontent.com/42288570/154808130-a3ffec57-5748-4814-b6eb-bf73d27fd20d.mp4

```python
import numpy as np
import panel as pn
import panel_highcharts as ph
import panel as pn
import pandas as pd
import numpy as np


pn.extension('highstock', sizing_mode="stretch_width", template="fast")

PRIMARY_COLOR = "#0072B5"

CSS_FIX = """
.highcharts-range-selector-buttons > g {
	visibility: unset;
}

.highcharts-navigator {
	visibility: unset;
}
"""
if not CSS_FIX in pn.config.raw_css:
    pn.config.raw_css.append(CSS_FIX)

DESCRIPTION = f"""
A user had problems using PANEL-HIGHCHARTS in tabs. 

It turns out a little bit of *css* could solve the problem.

```css
{CSS_FIX}
```
"""

def convert_returns(returns):
    prices = (1 + returns).cumprod().to_list()
    timestamps = list(returns.index.map(lambda x: int(float(x.to_datetime64()) / 1_000_000)))
    return list(map(list, zip(timestamps, prices)))


def plot_returns_highcharts(returns):
    data = convert_returns(returns)
    configuration = {
        "rangeSelector": {
            "inputEnabled": False,
        },
        "series": [
            {"name": "series", "type": "line", "data": data, "tooltip": {"valueDecimals": 2}}
        ],
        "yAxis": {
            "labels": {
                "formatter": """function () {
                    return (this.value > 0 ? ' + ' : '') + this.value + '%';
                }"""
            },
            "plotLines": [{
                "value": 0,
                "width": 2,
                "color": 'silver'
            }]
        },
        "plotOptions": {
            "series": {
                "compare": 'percent',
                "showInNavigator": True
            }
        },
    }
    chart = ph.HighStock(object=configuration)
    return chart

returns = pd.Series(np.random.normal(0, 0.01, 1_000),
                    index=pd.date_range("2000-01-01", freq="D", periods=1_000))

dashboard = pn.Column(
    pn.pane.Markdown("## Using HighStocks in tabs", margin=(10,0)),
    pn.Tabs(
        ("Description", pn.pane.Markdown(DESCRIPTION)),
        ("Chart", plot_returns_highcharts(returns)),
        tabs_location="above", margin=(0,15)
    )
)

dashboard.servable()

pn.state.template.param.update(
    site="Panel-HighCharts",
    accent_base_color=PRIMARY_COLOR, header_background=PRIMARY_COLOR,
)
```

**Comment by MarcSkovMadsen** [comment]
@thetradingflow and @govinda18

- Is the manual fix enough?
- Should it be on HighCharts end to fix this?
- Should Panel-HighCharts add a fix?

I am asking because there is no straightforward way today to add custom css to the Panel-HighCharts package. So it would be easier just to document the solution or even better that HighCharts fixed it on their end.

**Comment by MarcSkovMadsen** [comment]
@thetradingflow . Please link up on LinkedIn if its ok. I would really like to connect to users of this package. Thanks.

https://www.linkedin.com/in/marcskovmadsen/

**Comment by govinda18** [comment]
> Is the manual fix enough?

I think yes, that's what I have done too.

> Should it be on HighCharts end to fix this?

Yes, this would affect most tab layouts which usually uses visiblity to hide a tab.

> Should Panel-HighCharts add a fix?

Given that panel allows you to add custom css, I think we can consider documenting it instead. 

This is affecting us as well. I will check with the highcharts team once on an ETA for this.

**Comment by MarcSkovMadsen** [comment]
I will close this then. Feel free to open again if something should be done here.

**Comment by thetradingflow** [comment]
> @thetradingflow and @govinda18
> 
> * Is the manual fix enough?
> * Should it be on HighCharts end to fix this?
> * Should Panel-HighCharts add a fix?
> 
> I am asking because there is no straightforward way today to add custom css to the Panel-HighCharts package. So it would be easier just to document the solution or even better that HighCharts fixed it on their end.

The fix worked for me (I did the same). I agree with @govinda18, as a user without much experience with `panel` and `highcharts`, it's simple enough to fix that documenting it seems enough. Thanks guys!

**Comment by thetradingflow** [comment]
> @thetradingflow . Please link up on LinkedIn if its ok. I would really like to connect to users of this package. Thanks.
> 
> https://www.linkedin.com/in/marcskovmadsen/

Sorry, I'm not on Linkedin.
